### ISSUE TITLE
Proxies require lowercase

### ISSUE THREAD

**Issue by Sp5rky** [devine-dl/devine#88]
**Describe the bug**
When typing the proxy_providers in capitals for the 2 letter countries it fails

**To Reproduce**
In devine.yaml adding the proxies causes --proxy basic:JP or basic:jp to not be recognized and fails to connect

```
proxy_providers:
  basic:
    JP:
      - https://<user>:<password>@<host>:<port>
    SG: 
      - https://<user>:<password>@<host>:<port>
    PH:
      - https://<user>:<password>@<host>:<port>
```

**Expected behavior**
Connect to proxy regardless of capitals

**Screenshots**
![1](https://github.com/devine-dl/devine/assets/29722511/7a87799b-0edd-4e10-af33-579b5166a8c1)
![2](https://github.com/devine-dl/devine/assets/29722511/3db8e08e-ee9d-419f-8138-b5cdfb596abd)

**Additional context**
changing the devine.yaml to lowercase like the --proxy basic:jp now works correctly 

```
proxy_providers:
  basic:
    jp:
      - https://<user>:<password>@<host>:<port>
    sg: 
      - https://<user>:<password>@<host>:<port>
    ph:
      - https://<user>:<password>@<host>:<port>
```
